### ISSUE TITLE
Caché WEB Terminal v4

### ISSUE THREAD

**Issue by ZitRos** [intersystems-ru/webterminal#61]
Major update is coming. It should fix a lot of fails with the terminal I/O and improve user experience.

You can [download](http://intersystems-ru.github.io/webterminal/#downloads) an alpha version today!

Before the release there is some work in progress:
- [x] Refactor and prepare the repository:
  - [x] Replace XML with UDL *.cls;
  - [x] Improve back-end build scripts;
  - [x] Replace ES5 JavaScript with ES6 JavaScript modules;
  - [x] Improve JavaScript build scripts;
  - [x] Restore favorites feature;
  - [x] Restore tracing feature.
- [x] Improve back end:
  - [x] Rewrite WebTerminal's core, implement interprocess communication via $System.Event;
  - [x] Test `EscapeSequencesDemo.mac` utility.
- [x] Sync backend and frontend:
  - [x] Change messaging protocol to JSON.
- [x] Improve front end:
  - [x] Fix centering layout (make it not centering, as it causes inconsistent view in case when WebTerminal is a frame);
  - [x] Fix multi-line input caret position accuracy;
  - [x] Fix input capturing behavior;
  - [x] Fix mobile input;
  - [x] Rewrite output core;
  - [x] Test escape sequences, including case #63.
- [x] Improve installer:
  - [x] Complete issue #46;
  - [x] Add installation statistics collection.
- [x] Improve updater:
  - [x] Auto-update check #64;
  - [x] Review update mechanism.
- [x] WebTerminal client API
  - [x] Print;
  - [x] Execute (#68).
- [x] Syntax Highlighting
  - [x] Intelligent syntax highlighting core;
  - [x] Basic set of rules;
  - [x] Extended set of rules;
  - [x] Advanced set of rules.
- [x] Autocomplete (#58) (acceptable for the release)

[Subject to change]

You are welcome to suggest/discuss any changes that have to be included in `v4` release!

**Comment by ZitRos** [comment]
Definitions and themes features are dropped. Please, submit a new issue if you still need this features.
